### ISSUE TITLE
Change it to GECCO format

### ISSUE THREAD

**Issue by JJ** [Laucalle/AngryBirdsLevelGenerationThesis#31]
And adjust length if needed.

**Comment by amorag** [comment]
I'm working on this.
I'll finish by this evening.

The format has changed a lot since there is a new CLS file with a huge amount of dependences of other packages.

Please, stay tuned. :D

**Comment by amorag** [comment]
Done.
The new format is very complex regarding the high amount of packages it references.
So, it is quite frequent to have errors in compilation when you want to use other packages.

For instance, I am not able to apply the ACM bib style to the bibliography. :(

Anyway, I think the format is ok now, so we could work on this TEX file.

Finally, I'm not sure if I can close an issue from a pull request... :(
